### ISSUE TITLE
[클리앙] URL이 접속되지 않습니다.

### ISSUE THREAD

**Issue by JJUUUN** [ImBada/SearchEverythingForMac#1]
안녕하세요. 이런 글을 올리는 것은 맞지 않지만,
클리앙에서 검색한 결과로 들어왔습니다.

클리앙에 올려주신 GitHub Url이 접속되지 않습니다.
https://imbada.github.io/SearchEverythingForMac/

감사합니다.

**Comment by ImBada** [comment]
안녕하세요. 방금 확인했는데 접속에 문제가 없는 것으로 보입니다. 
사용하시는 브라우저나 인터넷 환경을 알 수 있을까요? 접속이 안 되는 경우 오류 화면도 부탁드리겠습니다
